### PR TITLE
Add RHEL 7 build settings to contrib/redhat/openssh.spec

### PR DESCRIPTION
**Pull request by nkadel**
Use %global instead of %define univerally.
Add epoch numbers for openssl dependencies on RHEL 7
Require /usr/bin/login intead of /bin/login for RHEL compatibility

### CODE REVIEW

**Comment by daztucker** [comment]
I had a look at these prior to the release, but the commits don't explain *why* some of the changes were made, in particular the define->global one, and most of the others depend on that.

**Comment by nkadel** [comment]
Oh! %global is now considered standard for all .spec files in every RHEL and Fedora release.

**Comment by nkadel** [comment]
Would you like the switch to '%global" as a different pull request?

**Comment by nkadel** [comment]
I'll re-merge after pull request 156, when %define gets switched to the RHEL default %global.

**Pull request closed without merging**
