### PR TITLE
Add support for AUDIT_ARCH_RISCV64

### PR DESCRIPTION
**Pull request by andreas-schwab**

### CODE REVIEW

**Comment by Tomes111** [comment]
Gists
Comments in Issues and Pull Requests
Files with the .md or .markdown extension

**Comment by Tomes111** [comment]
Gists
Comments in Issues and Pull Requests
Files with the .md or .markdown extension

**Comment by Tomes111** [comment]
#

**Comment by Tomes111** [comment]
sl4a
Forked from kuri65536/sl4a

Scripting environment for Android platform

**Comment by daztucker** [comment]
applied, thanks.

**Pull request closed without merging**
