### PR TITLE
sftp-server: Add support for BSD style advisory file locking operations

### PR DESCRIPTION
**Pull request by kalvdans**
Only non-blocking shared or exclusive locks are supported for now. Allocate a new extension string for the flock operations.

### CODE REVIEW

**Comment by kalvdans** [comment]
The corresponding changes in sshfs that takes advantage of this protocol extension can be viewed at: https://github.com/libfuse/sshfs/pull/55

**Comment by estan** [comment]
We're waiting eagerly for this feature. It would be great if a maintainer could take a look at this PR.

**Comment by Jakuje** [comment]
If you are interested in these changes in OpenSSH, you should fill the bug report on http://bugzilla.mindrot.org/ -- the github is used only as a mirror, as already said many times.

**Comment by estan** [comment]
@Jakuje Aha, did not know that, sorry for the noise. @kalvdans would you mind filing a bug with the patch at Bugzilla?

**Comment by kalvdans** [comment]
Thanks @Jakuje, a bug has been posted to https://bugzilla.mindrot.org/show_bug.cgi?id=2828

**Comment by djmdjm** [comment]
Sorry, but we have no desire to add file locking to sftp/sftp-server. In fact, addition of file locking feature to the sftp protocol was why we never implemented versions of the protocol after 3.

**Comment by djmdjm** [comment]
Also, please use https://bugzilla.mindrot.org/ instead of github PRs in future. We only use this site as a mirror and seldom check the PR queue.

**Pull request closed without merging**
