### PR TITLE
Add CIFuzz integration

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz, on which Openssh already runs (https://github.com/google/oss-fuzz/tree/master/projects/openssh)

### CODE REVIEW

**Comment by daztucker** [comment]
I don't think this will work since we currently don't allow any third party workflows on the OpenSSH project.

**Comment by DavidKorczynski** [comment]
Okay - I am happy to leave this open in case your policy changes and feel free to close the issue if you prefer

**Comment by daztucker** [comment]
We now allowlist a Cygwin workflow for testing purposes, we could probably extend the allowlist and enable this now.

**Comment by daztucker** [comment]
Applied, thanks.  I'm still fiddling with the allowlist settings.

**Pull request closed without merging**
